config/routes.rb
Rails.application.routes.draw do
  root :to => 'photos#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :photos
  resources :tags
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :img, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "images/:style/missing.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  has_many :tags
  has_many :users, through: :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tags
  has_many :photos, through: :tags
  has_secure_password
  validates :name, presence: true,
                   uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authorize, only: [:edit, :update]

  def index
    @photos = Photo.all
  end

  def create
    @user = current_user
    @photo = @user.photos.create(strong)
    @tag = Tag.find_by_photo_id(@photo.id)
    @tag.update({ owner: true })
    redirect_to user_path(@user)
  end

  def show
    @tag = Tag.new
    @photo = Photo.find(params[:id])
    @user = User.find(Tag.all.where(photo_id: @photo.id, owner: true).first.user_id)
    @new_array = (User.all - [@user]).map { |user| user}
    @user_array = @new_array.map { |user| [user.name, user.id]}
  end

  private

  def strong
    params.require(:photo).permit(:title, :img)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      hdjhskdjh.ddad
      session[:user_id] = user.id
      redirect_to '/', notice: 'Logged in successfully!'
    else
      redirect_to '/', notice: 'Name or password is invalid!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @photo = Photo.find(params[:tag][:photo_id])
    @tag = Tag.create(strong)
    redirect_to photo_path(@photo)
  end


  private

  def strong
    params.require(:tag).permit(:photo_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(strong)
    if @user.save
      session[:user_id] = @user.id
      redirect_to photos_path, notice: 'Logged in successfully!'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @photo = Photo.new
    @owner_photos = []
    @owner = @user.tags.where({ :owner => true })
    @owner.each do |tag|
      @owner_photos << Photo.find(tag.photo_id)
    end
    @tagged = @user.photos - @owner_photos

  end


  private

  def strong
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phliker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] %>
<div class="loginmenu">
<% if current_user %>
  Logged in as <%= current_user.name %>.<br>
  <%= link_to "Profile", user_path(current_user) %>
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= form_tag sessions_path do %>
    <div class="field">
      <%= label_tag :name %><br />
      <%= text_field_tag :name, params[:name] %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions"><%= submit_tag "Log In" %></div>
  <% end %>
  <a href ="/signup/"><button>Sign Up</button></a>
<% end %>
</div>

<%= yield %>

<% if !current_page?("/") %>
  <hr>
  <%= link_to "Back to home page", "/" %>
<% end %>
</body>
</html>

app/views/photos/index.html.erb
<h1>Welcome to Phliker!!</h1>

  <% @photos.each do |photo| %>
    <a href="photos/<%= photo.id %>"><%= image_tag photo.img(:thumb) %></a>
  <% end %>

app/views/photos/show.html.erb
<h1>Photo</h1>
<h3>Owner: <%= @user.name %></h3>

<a href="/users/<%= @user.id %>"><%= image_tag @photo.img %></a>
<hr>
Tag other user with this photo

<%= form_for(@tag) do |f| %>
  <div class="field">
    <%= f.hidden_field(:photo_id, :value => "#{@photo.id}") %>
    <%= f.select(:user_id, options_for_select(@user_array)) %>
  </div>

  <div class="actions"><%= f.submit "Tag!" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render 'layouts/errors', :object => @user %>
<div id="create">
  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Your Photos</h3>
<% @owner_photos.each do |photo| %>
  <%= image_tag photo.img(:medium) %>
<% end %>

<h3>Tagged photos</h3>
<% @tagged.each do |photo| %>
  <%= image_tag photo.img(:medium) %>
<% end %>

<hr>
<%= form_for @photo, :url => photos_path, :html => { :multipart => true } do |form| %>
  <div class="field">
    <%= form.file_field :img %>
  </div><br>
  <div class="actions"><%= form.submit "Submit" %></div>
<% end %>